coverage:
  status:
    project:
      default:
        # basic
        target: 20%
        threshold: 0%
        base: auto
        flags:
          - unit
#        paths:
#          - "src"
        # advanced settings
        branches:
          - main
        if_ci_failed: ignore #success, failure, error, ignore
        informational: false
        only_pulls: false