version: '3.8'

services:
  apache:
    image: httpd
    container_name: apache-webserver
    cap_add:
      - NET_ADMIN
    ports:
      - 443:443
      - 80:80
    restart: unless-stopped
  mysql:
    container_name: mysql-server
    image: mysql
    expose:
      - '3306'
    ports:
      - '3306:3306'
    restart: always

  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - '3001'
    ports:
      - '3001:3001'
    restart: unless-stopped